# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2019-06-01 20:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='movie_art',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='trivia',
            name='trivia',
            field=models.CharField(max_length=1000),
        ),
    ]
