# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2019-06-02 12:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0003_auto_20190602_0700'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='movie_art',
            field=models.FileField(blank=True, max_length=1000, upload_to=''),
        ),
    ]
