# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2019-06-02 12:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0004_auto_20190602_1213'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trivia',
            name='trivia_details',
            field=models.TextField(max_length=1000),
        ),
    ]
